### ISSUE TITLE
type name are changed

### ISSUE THREAD

**Issue by Benoit-ROBIN** [ardeois/graphql-codegen-typescript-mock-data#115]
Hi, 
does anyone know why my type's name are not keep from generated type's file ? 
For example: 
In my generated type's file I have a type named `Bo_AllActivityGroupPayload` and in the mock file generated by `typescript-mock-data` this type become `Bo_AllActivityGroupPayload`, so the import is broken and nothing work. 

here's my conf:

```yml
overwrite: true
schema: ${BACKEND_URL}
documents: 'src/**/*.{ts,tsx}'
generates:
  src/types/generated-ops.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
  src/types/fragmentTypes.json:
    plugins:
      - 'fragment-matcher'
  src/__tests__/generated-mocks.ts:
    plugins:
      - typescript-mock-data:
          typesFile: '../types/generated-ops.ts'
          generateLibrary: 'faker'
          typeNames: keep
          enumValues: keep
          terminateCircularRelationships: true
```
