### ISSUE TITLE
issue with enum transformation

### ISSUE THREAD

**Issue by Benoit-ROBIN** [ardeois/graphql-codegen-typescript-mock-data#116]
Hi 
I tried to have my enum generated in pascalCase (key and value), but in my case only the keys are transformed to pascalCase, the value stay in snakeCase. 
I have seen [this pr](https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/75/files) and I thought maybe it was overwritten accidentally ? 

here my config 
```yml
overwrite: true
schema: ${BACKEND_URL}
documents: 'src/**/*.{ts,tsx}'
generates:
  src/types/generated-ops.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
  src/types/fragmentTypes.json:
    plugins:
      - 'fragment-matcher'
  src/__tests__/generated-mocks.ts:
    plugins:
      - typescript-mock-data:
    config:
      typesFile: '../types/generated-ops.ts'
      generateLibrary: 'faker'
      typeNames: 'change-case-all#pascalCase'
      enumValues: 'change-case-all#pascalCase'
      transformUnderscore: false
      terminateCircularRelationships: true
```
I have set transformUnderscore to false because I need to keep underscore on my type's name.
