### ISSUE TITLE
Won't respect typesPrefix: "I"

### ISSUE THREAD

**Issue by berkaey** [ardeois/graphql-codegen-typescript-mock-data#135]
Hi, our settings file goes like this 
```
overwrite: true
schema: "http://localhost:3000/graphql"
generates:
  constants/mocks/index.ts:
    plugins:
      - typescript-mock-data:
          typesFile: "../../types"
          enumValues: upper-case#upperCase
          typeNames: change-case-all#pascalCase
          typesPrefix: "I"
          prefix: "Mock"
          addTypename: true
          generateLibrary: faker
          terminateCircularRelationships: true
          scalars:
            Date:
              generator: date.past
              arguments: 10
            ID:
              generator: database.mongodbObjectId
          fieldGeneration:
            _all:
              email: internet.email
              bio: lorem.paragraph
              firstName: name.firstName
              lastName: name.lastName
              fullName: name.fullName
              title: company.name
            File:
              key: undefined
            FileURLs:
              original: image.abstract
            FileStream:
              url: undefined
```

and our types generator goes like this 

```
overwrite: true
schema: "http://localhost:3000/graphql"
generates:
  types/index.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      declarationKind:
        type: "interface"
        input: "interface"
      typesPrefix: "I"
      enumPrefix: false
      enumsAsConst: true
      maybeValue: T
      namingConvention:
        enumValues: keep
  types/apollo.ts:
    plugins:
      - fragment-matcher
    config:
      apolloClientVersion: 3
``

This was working until today but today, generator generates like below;
```
emails:
      overrides && overrides.hasOwnProperty("emails")
        ? overrides.emails!
        : [
            relationshipsToOmit.has("Email")
              ? ({} as Email)
              : MockEmail({}, relationshipsToOmit),
          ],
```

but it should be 

```
emails:
      overrides && overrides.hasOwnProperty("emails")
        ? overrides.emails!
        : [
            relationshipsToOmit.has("IEmail")
              ? ({} as IEmail)
              : MockEmail({}, relationshipsToOmit),
          ],
```
