### ISSUE TITLE
Mocks do not respect aliases

### ISSUE THREAD

**Issue by davidgtu** [ardeois/graphql-codegen-typescript-mock-data#149]
I have an query that uses aliases like so:

```graphql
 ... on AttributeBoolean {
          booleanValue: value
        }
        ... on AttributeDate {
          dateValue: value
        }
        ... on AttributeDatetime {
          datetimeValue: value
        }
        ... on AttributeFloat {
          floatValue: value
        }
        ... on AttributeInteger {
          integerValue: value
        }
        ... on AttributeString {
          stringValue: value
        }
```

However, when I generate my mock data, it seems to retain `value`  rather than `booleanValue` etc.

My config currently looks like this:

```yml
generates:
  ./src/generated/generated-mock.ts:
    plugins:
      - typescript-mock-data:
          typesFile: ./graphql.ts
          typeNames: pascal-case#pascalCase
          useImplementingTypes: true
          scalars:
            AWSTimestamp: unix_time # gets translated to casual.unix_time
```
