### ISSUE TITLE
Types are not imported in the generated mocks

### ISSUE THREAD

**Issue by mdazy** [ardeois/graphql-codegen-typescript-mock-data#15]
Hello,

the generated code appears to use the generated types without ever importing them first. As a result, as soon as I try to use one of the mock functions, I'm getting errors for each generated mock:
```
    schema/lib/mocks.tsx:214:55 - error TS2304: Cannot find name 'Status'.
    214 export const aStatus = (overrides?: Partial<Status>): Status => {
                                                    ~~~~~~
``` 

My codegen config is like this:
```
schema: ./schema/lib/schema.json
documents: ./schema/*.graphql
generates:
  ./schema/lib/clientTypes.tsx:
    plugins:
      - add: /* tslint:disable */
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withHOC: false
      withComponent: false
  ./schema/lib/mocks.tsx:
    plugins:
      - graphql-codegen-typescript-mock-data:
        typesFile: ./clientTypes.tsx
```

I'm pretty sure I must be missing something very basic but I just can't figure out what.

Thanks,
