### ISSUE TITLE
defaultNullableToNull should use null for custom Scalars

### ISSUE THREAD

**Issue by tjmgregory** [ardeois/graphql-codegen-typescript-mock-data#155]
The newly implemented `defaultNullableToNull` option should take precedence over custom Scalar definitions as you cannot define those optionally and are global.

As implemented in https://github.com/ardeois/graphql-codegen-typescript-mock-data/pull/130 it makes sense for specific field configuration to take precedence over `defaultNullableToNull`.

Precedence of options should be `fieldGeneration` > `defaultNullableToNull` > `scalars`.

If folks agree I'm happy to give this a crack in the coming days.

### Example GQL Schema

```gql
type Hat {
  id: ID!
  description?: String
}
```

### Example config

```yaml
  src/__generated__/test-fixtures.gql.ts:
    plugins:
      - add:
          content: "import { faker } from '@faker-js/faker';"
      - typescript-mock-data:
          typesFile: ./base.gql.ts
          defaultNullableToNull: true
          scalars:
            ID: faker.string.uuid()
            String: faker.word.words()
            Boolean: faker.datatype.boolean()
```

### Current output

```ts
export const aHat = (overrides?: Partial<Hat>): Hat => {
  return {
    id: overrides && overrides.hasOwnProperty('id') ? overrides.apiKeyName! : faker.string.uuid(),
    description: overrides && overrides.hasOwnProperty('description') ? overrides.apiKeyName! : faker.word.words(),
  }
}
```

### Expected output

```ts
export const aHat = (overrides?: Partial<Hat>): Hat => {
  return {
    id: overrides && overrides.hasOwnProperty('id') ? overrides.apiKeyName! : faker.string.uuid(),
    description: overrides && overrides.hasOwnProperty('description') ? overrides.apiKeyName! : null,
  }
}
```

**Comment by ardeois** [comment]
Thanks for the suggestion @tjmgregory
I agree `defaultNullableToNull` should take precedence over `scalars`
Feel free to open a PR

A little side note, you don't need to add your own faker import and generators, it's builtin by the plugin, you just need to change the default generator:
```yaml
  src/__generated__/test-fixtures.gql.ts:
    plugins:
      - typescript-mock-data:
          typesFile: ./base.gql.ts
          defaultNullableToNull: true
          generateLibrary: faker
          scalars:
            ID: string.uuid
            String: word.words
            Boolean: datatype.boolean
```
