### ISSUE TITLE
How to deal with the cyclic reference?

### ISSUE THREAD

**Issue by pavelmasekcmgx** [ardeois/graphql-codegen-typescript-mock-data#162]
Is there some kind of common way how to deal with the cyclic reference of the graph? 

Let's imagine graph like this one. 
```
type Query {
  user(id: ID): User
  location(id: ID): Location
}

type User {
  id: ID!
  ...
  location?: Location
}

type Location {
  id: ID!
  ...
  user?: User
}
```
that will generate mock functions
```
function anUser(...) {...}
function aLocation(...) {...}
```
calling those functions will result in `Maximum call stack size exceeded`

I can imagine something like altering of the `fieldGeneration` in the plugin config.

```
fieldGeneration:
  User:
    location: aLocation({user: null})
  Location:
    user: anUser({location: null})
```

but this becomes quite complicated in case of more complex graph where the cyclic reference appears on some nested levels.
