### ISSUE TITLE
Rename JSONFilter and UUIDFilter to JsonFilter and UuidFilter

### ISSUE THREAD

**Issue by naknode** [ardeois/graphql-codegen-typescript-mock-data#66]
This plugin is great except for the fact that I have to rename `JSONFilter` and `UUIDFilter` to `JsonFilter` and `UuidFilter` everywhere after every `codegen`.

Is there a way to bypass this or does an MR need to be submitted?

Here is my `build_local_types.yml`:

```yml
  mocks/generated-local-mocks.ts: ## Generate a local mocked data generator
    plugins:
      - typescript-mock-data:
          typesFile: '../src/types/types.ts'
          enumValues: keep
          terminateCircularRelationships: true
          skipTypename: true
          typenames: keep
          prefix: 'mock'
          scalars:
            Date: date
            Datetime: date
```
