### ISSUE TITLE
Generated Mock File Doesn't Import Types?

### ISSUE THREAD

**Issue by CowDotDev** [ardeois/graphql-codegen-typescript-mock-data#74]
My apologies if I am just missing something dumb - but I have implemented this typescript-mock-data plugin and am seeing the functions generated successfully. However, the `generated-mocks.ts` files does not import any of the types from the `generated-types.ts` file so TypeScript compilation fails on this file.

What do I need to do in order to have the `generated-mock.ts` file reference the types graphql-codegen generates?

Thank you in advanced!

`codegen.yml`
```
overwrite: true
schema: 'schema.graphql'
documents: 'src/graphql/operations/**/*.ts'
generates:
  src/graphql/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
  src/mocks/generated-mocks.ts:
    plugins:
      - typescript-mock-data:
        typesFile: 'src/graphql/generated.ts'
        enumValues: upper-case#upperCase
        typenames: keep
        scalars:
          ConnectionCursor:
            generator: word
          DateTime:
            generator: date
            arguments: 'YYYY-MM-DDTHH:mm:ssZ'
          JSON:
            # TODO: This shouldn't be currency, but typescript-mock-data plug-in does not support custom casual generators, yet.
            # TODO: Possibly look into extending typescript-mock-data to accept custom casual generators
            # https://github.com/boo1ean/casual#define-custom-generators
            generator: currency
          JSONObject:
            # TODO: This shouldn't be currency, but typescript-mock-data plug-in does not support custom casual generators, yet.
            # TODO: Possibly look into extending typescript-mock-data to accept custom casual generators
            # https://github.com/boo1ean/casual#define-custom-generators
            generator: currency
  ./graphql.schema.json:
    plugins:
      - 'introspection'
```
