### ISSUE TITLE
Enum field names don't get resolved the same as codegen typescript plugin by default

### ISSUE THREAD

**Issue by farmstrong8** [ardeois/graphql-codegen-typescript-mock-data#82]
There is a naming mismatch when generating the mock data. For example if you have this enum, it gets resolved as:

```jsx
// Enum
export enum Sort {
    createdDate = "createdDate",
    _id = "_id",
}

// codegen typescript
export enum Sort {
  Id = '_id',
  CreatedDate = 'createdDate'
}
```

when Id is referenced in the mock data it gets called using ._Id instead of .Id

```jsx
...
return {
        ...
        sortBy: overrides && overrides.hasOwnProperty('sortBy') ? overrides.sortBy! : Sort._Id,
    };
```

codegen.yml

```yml
generates:
    ./src/generated-gql.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - typescript-resolvers
            - typescript-apollo-client-helpers
            - fragment-matcher
    ./tests/mocks/generated-mocks.ts:
        plugins:
            - typescript-mock-data
        config:
            typesFile: "../../src/generated-gql.ts"
            terminateCircularRelationships: true
```
